## Q.1. Numerical Operations

In [119]:
import numpy as np

In [120]:
units_sold=np.array([10,25,40,35,50])
units_sold

array([10, 25, 40, 35, 50])

In [121]:
unit_price=np.array([100,150,200,120,180])
unit_price

array([100, 150, 200, 120, 180])

In [122]:
total_sales=units_sold*unit_price
total_sales

array([1000, 3750, 8000, 4200, 9000])

In [123]:
overall_sales=np.sum(total_sales)
overall_sales

25950

## Q.2. Indexing and Filtering

In [124]:
#Using NumPy arrays
units_sold=np.array([10,25,40,35,50])
profit = np.array([200, 300, 500, 400, 700])

In [125]:
result = units_sold[units_sold > 30]
result

array([40, 35, 50])

In [126]:
profit = profit[units_sold > 30]
profit

array([500, 400, 700])

In [127]:
avg_profit=np.mean(profit)
avg_profit

533.3333333333334

In [128]:
import pandas as pd

In [129]:
#Using Pandas

data={
    "Units_Sold": [10, 25, 40, 35, 50],
    "Unit_Price": [100, 150, 200, 120, 180],
    "Profit": [200, 300, 500, 400, 700]
}
data

{'Units_Sold': [10, 25, 40, 35, 50],
 'Unit_Price': [100, 150, 200, 120, 180],
 'Profit': [200, 300, 500, 400, 700]}

In [130]:
df=pd.DataFrame(data)

In [131]:
df.head()

Units_Sold  Unit_Price  Profit
0          10         100     200
1          25         150     300
2          40         200     500
3          35         120     400
4          50         180     700

In [132]:
df.dtypes

Units_Sold    int64
Unit_Price    int64
Profit        int64
dtype: object

In [133]:
result=df[df["Units_Sold"]>30]
result

Units_Sold  Unit_Price  Profit
2          40         200     500
3          35         120     400
4          50         180     700

In [134]:
avg_profit=result["Profit"].mean()
avg_profit

533.3333333333334

## Q.3. Data Loading and Inspection

In [142]:
data = {
    "Product": ["Laptop", "Mouse", "Keyboard", "Monitor", "Tablet"],
    "Region": ["North", "South", "East", "West", "North"],
    "Units_Sold": [10, 25, 40, 35, 50],
    "Unit_Price": [100, 150, 200, 120, 180],
    "Profit": [2000, 900, 500, 4500, 700]
}
data

{'Product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Tablet'],
 'Region': ['North', 'South', 'East', 'West', 'North'],
 'Units_Sold': [10, 25, 40, 35, 50],
 'Unit_Price': [100, 150, 200, 120, 180],
 'Profit': [2000, 900, 500, 4500, 700]}

In [143]:
df.head()

Product Region  Units_Sold  Unit_Price  Profit  Revenue
0    Laptop  North          10         100    2000     1000
1     Mouse  South          25         150     900     3750
2  Keyboard   East          40         200     500     8000
3   Monitor   West          35         120    4500     4200
4    Tablet  North          50         180     700     9000

In [144]:
df.dtypes

Product       object
Region        object
Units_Sold     int64
Unit_Price     int64
Profit         int64
Revenue        int64
dtype: object

In [145]:
df.describe()

Units_Sold  Unit_Price       Profit      Revenue
count    5.000000    5.000000     5.000000     5.000000
mean    32.000000  150.000000  1720.000000  5190.000000
std     15.247951   41.231056  1658.915308  3279.557897
min     10.000000  100.000000   500.000000  1000.000000
25%     25.000000  120.000000   700.000000  3750.000000
50%     35.000000  150.000000   900.000000  4200.000000
75%     40.000000  180.000000  2000.000000  8000.000000
max     50.000000  200.000000  4500.000000  9000.000000

## Q.4. Data Manipulation

In [146]:
df=pd.DataFrame(data)

In [147]:
df["Revenue"] = df["Units_Sold"] * df["Unit_Price"]
df

Product Region  Units_Sold  Unit_Price  Profit  Revenue
0    Laptop  North          10         100    2000     1000
1     Mouse  South          25         150     900     3750
2  Keyboard   East          40         200     500     8000
3   Monitor   West          35         120    4500     4200
4    Tablet  North          50         180     700     9000

In [148]:
df.groupby("Region")["Revenue"].sum()

Region
East      8000
North    10000
South     3750
West      4200
Name: Revenue, dtype: int64

In [149]:
df.groupby("Product")["Profit"].sum().idxmax()

'Monitor'

## Grouping and Aggregation

In [150]:
df.groupby("Product")["Unit_Price"].mean()

Product
Keyboard    200.0
Laptop      100.0
Monitor     120.0
Mouse       150.0
Tablet      180.0
Name: Unit_Price, dtype: float64

In [151]:
df["Region"].value_counts()

Region
North    2
South    1
East     1
West     1
Name: count, dtype: int64

In [152]:
df.groupby("Product")["Units_Sold"].max()

Product
Keyboard    40
Laptop      10
Monitor     35
Mouse       25
Tablet      50
Name: Units_Sold, dtype: int64

## Data Filtering

In [153]:
df[df["Profit"] > 1000]

Product Region  Units_Sold  Unit_Price  Profit  Revenue
0   Laptop  North          10         100    2000     1000
3  Monitor   West          35         120    4500     4200

In [154]:
df.sort_values(by="Revenue", ascending=False)

Product Region  Units_Sold  Unit_Price  Profit  Revenue
4    Tablet  North          50         180     700     9000
2  Keyboard   East          40         200     500     8000
3   Monitor   West          35         120    4500     4200
1     Mouse  South          25         150     900     3750
0    Laptop  North          10         100    2000     1000

In [155]:
df[df["Product"] == "Laptop"]

Product Region  Units_Sold  Unit_Price  Profit  Revenue
0  Laptop  North          10         100    2000     1000